### ISSUE TITLE
Install kubectl for CI builds

### ISSUE THREAD

**Issue by cassand** [GoogleCloudPlatform/openjdk-runtime#101]
The integration test on GKE need kubectl to be installed in order to deploy the test application. 
The kubectl executable is currently not available during CI build and need to be installed in the cloud-init script.

**Comment by meltsufin** [comment]
@aslo So the master branch CI build should be failing, but I didn't see any build failure notifications.

**Comment by aslo** [comment]
There was an email that you should have gotten yesterday. Perhaps we need to do a better job of separating the signal from the noise in those build notification emails.

**Comment by meltsufin** [comment]
Ah! you're right! I see it now. Never mind.
