### ISSUE TITLE
Adding `DBG_ENABLE: true` to app.yaml disables Cloud Debugger

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/openjdk-runtime#107]
```yaml
env_variables:
   DBG_ENABLE: true
```

**Comment by starkenburgs** [comment]
Cloud Debugger is also disabled when setting DBG_ENABLE to false.

**Comment by meltsufin** [comment]
It looks like the root cause is that yaml `true` is a boolean and gets stringified for env to `'True'`, not `'true'`.
