### ISSUE TITLE
Setup local integration test with the runtimes-common integration testing

### ISSUE THREAD

**Issue by balopat** [GoogleCloudPlatform/openjdk-runtime#126]
Via running the ``gcr.io/gcp-runtimes/integration_test`` image locally (same functionality as in integration_test.yaml), we could actually iterate much faster when implementing changes on the test-app. 
Currently the local_integration_test.sh is only testing whether the app starts and verifies the shutdown logs.

**Comment by meltsufin** [comment]
I believe `gcr.io/gcp-runtimes/integration_test` is not able to verify shutdown logs. So, I assume you're not proposing to replace `local_integration_test.sh`? Maybe we should rename it to `local_shutdown_test.sh` or something.

**Comment by balopat** [comment]
I am not proposing replacing it, just extending it. I think it's fine to test the shutdown logs as well as the integration tests in the same integration test script. This in effect would be just 1-2 lines of change. I almost have it working.
