### ISSUE TITLE
Fix flaky monitoring integration test

### ISSUE THREAD

**Issue by balopat** [GoogleCloudPlatform/openjdk-runtime#127]
The monitoring integration test is flaky. 
The following are the main reasons: 

1. The driver can't find the custom metric

BadRequest: 400 The provided filter doesn't refer to any known metric. (GET https://monitoring.googleapis.com/v3/projects/java-runtime-test/timeSeries/?filter=metric.type+%3D+%22custom.googleapis.com%2FUzLlwfHpNOCsZSuu%22&interval.endTime=2017-08-03T21%3A13%3A00.000000Z&interval.startTime=2017-08-03T21%3A11%3A00.000000Z)

Solution: reproduce the error and identify a workaround (work out timings, retries, double check if the metric is stored, etc.)

2. The gRPC call fails while storing the metric

exit code: 500, text: {"timestamp":1501793413295,"status":500,"error":"Internal Server Error","exception":"com.google.api.gax.grpc.ApiException","message":"io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: INTERNAL_ERROR\nReceived Rst Stream","path":"/monitoring"}

Solution: file a bug with the Stackdriver team and hunt down the root cause, and in the mean time catch the exception and retry (maybe double check if the metric was stored)

**Comment by meltsufin** [comment]
@nkubala has anyone successfully implemented this test from your common integration testing framework?

**Comment by nkubala** [comment]
> has anyone successfully implemented this test from your common integration testing framework?

@meltsufin @balopat I wrote the sample integration test application for Python myself, so you can use that as an example if you run into issues. Here's the monitoring test: https://github.com/GoogleCloudPlatform/python-runtime/blob/master/tests/integration/server.py#L140

**Comment by balopat** [comment]
thanks @nkubala based on what I see there is no significant difference from my implementation. 
The 400 error seems like a timing issue, it takes a long time for Stackdriver to actually expose the new custom metric, and even the 80 seconds are not enough sometimes ([8s x 10 retry](https://github.com/GoogleCloudPlatform/runtimes-common/blob/master/integration_tests/testsuite/test_monitoring.py#L46)). I'm wondering if the creation of a new metric at every request is necessary? I'd think that not having to create the new metric would speed things up, and would still count as a good integration test as long we write the token into the timeseries. 
If we don't do that, then I'd have to resort to waiting until the metric is created in the test app code.

**Comment by nkubala** [comment]
@balopat creating a new metric descriptor isn't necessary, but thought it would be a valid component of the test. if it's totally blocking your test from passing then we can revisit it, but I'd rather not make that change as other runtimes have been able to write the metrics successfully. could you maybe come up with a lower bound on the wait time for the metric to propagate to Stackdriver, and then we can just up the wait time in the test?

**Comment by balopat** [comment]
@nkubala I am working on a test suite to narrow down the issues with the StackDriver monitoring when creating a metric - sometimes even the 80 seconds are not enough, when I start reading "too quickly" after the metric was created. This suggests that creating new metrics is a "heavy" operation and can interfere with subsequent reads within a certain "cool down period", while with an already created metric I had absolutely no problem. 
But there is another (minor) problem with custom metrics: there is a [quota policy ](https://cloud.google.com/monitoring/quota-policy) for custom metrics - which I'm not sure everyone is aware of and would cause surprises down the line unless we setup cleanup logic for them.

**Comment by nkubala** [comment]
Yeah I think the main issue with the reading of the metric is that the propagation time/time it takes to flush the writes to Stackdriver varies greatly, so I think that sufficiently increasing the timeout there should probably solve that problem.

As for the quota, yeah that's something we'll need to address. We should probably just cleanup the metric descriptors we create in the tests. #302

**Comment by balopat** [comment]
@nkubala  I created a PR to tackle these: https://github.com/GoogleCloudPlatform/runtimes-common/pull/306
