### ISSUE TITLE
Debian 9 Stretch is out - perhaps we should upgrade ??

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/openjdk-runtime#132]
Actually 9.1 was released recently https://www.debian.org/releases/stretch/

**Comment by aslo** [comment]
The openjdk:9 image will use debian 9 ([see pull request](https://github.com/GoogleCloudPlatform/openjdk-runtime/pull/129)). @meltsufin We should probably update the openjdk:8 to use debian 9 as well - thoughts on when to do this?

**Comment by meltsufin** [comment]
I'm not sure how major of an upgrade it is from Debian 8 to 9. I would look for guidance from @dlorenc.

**Comment by lesv** [comment]
If this hasn't been done by now, it never will be.
