### ISSUE TITLE
Remove `DBG_ENABLE` from README.md

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/openjdk-runtime#161]
Looks like this is no longer used to enable / disable the debug agent ?

@saturnism FYI

**Comment by meltsufin** [comment]
Why do you say that? It's used, and it's on by default of App Engine.

**Comment by jabubake** [comment]
User error, looks like docs just need to be updated on default : https://cloud.google.com/debugger/docs/setup/app-engine-java
