### ISSUE TITLE
Cloud Debugger doesn't work w/ OpenJDK 9

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/openjdk-runtime#162]
Using the SparkJava sample in java-docs-samples /flexible/sparkjava I try and debug UserService.java getAllUsers  L55

I can set a watchpoint in OpenJDK8, but not in OpenJDK9

(Note - I got rid of the Dockerfile, updated app.yaml and changed the pom.xml to compile w/ 1.9 as well.

**Comment by meltsufin** [comment]
v2.17 of Cloud Debugger has been released, which should have support for Java 9. @ChengyuanZhao PTAL.

**Comment by ChengyuanZhao** [comment]
I will make a PR, but apparently this seems to be an issue with the base openjdk 9 image we use. 

Adding `RUN dpkg --purge --force-depends ca-certificates-java` before the `RUN apt-get -q update \
 && apt-get -y -q --no-install-recommends install \
    # install the jdk and its dependencies
    ca-certificates-java \` in our openjdk9 dockerfile resolves the issue I believe. 

@lesv could you give that a try and see if it works for you? We had this issue a while ago but somehow forgot to make a PR out of it. I just wanna make sure you're not seeing some other issue.

I will make a PR out of it too.

**Comment by meltsufin** [comment]
Is this branch https://github.com/GoogleCloudPlatform/openjdk-runtime/tree/jdk9-ca-certs ?

**Comment by ChengyuanZhao** [comment]
Wow you're quick, yea that's the one. Here's a PR of the change

https://github.com/GoogleCloudPlatform/openjdk-runtime/pull/168/files

**Comment by ChengyuanZhao** [comment]
Perhaps the stackdriver team worked around that issue I mentioned in the PR they originally encountered with the ca-certs, because I tried it with a test spark app and cloud debugger debug points worked and stopped properly for me.  I'll try to reproduce using Les's example.

**Comment by ChengyuanZhao** [comment]
Stop points do work in /flexible/sparkjava for me if I use a custom dockerfile, but I also see that if I use runtime: java and openjdk9 in app.yaml then it's not available for cloud debugging. I'll try to find out why.

**Comment by ChengyuanZhao** [comment]
Oh I forgot to mention, we only enable the cloud debugger agent if our jetty or tomcat runtime images are used. If you're instead deploying a JAR to appengine like with `mvn appengine:deploy`, then cloud debugger won't be enabled. The jar must be run with `-agentpath:/opt/cdbg/cdbg_java_agent.so` to enable cloud debugger. 

@meltsufin @lesv

**Comment by meltsufin** [comment]
I don't think that's true. Whether the agent is added is controlled in the [entrypoint](https://github.com/GoogleCloudPlatform/openjdk-runtime/blob/master/openjdk-common/src/main/docker/setup-env.d/20-debug-env.bash) via `DBG_ENABLE`, which is true by default on GAE.

**Comment by ChengyuanZhao** [comment]
Ah shoot my bad! you're right

**Comment by ChengyuanZhao** [comment]
I think the reason is the gcloud command is using an outdated version of our runtimes-builder, which is using the 2e8cd4717ce4 version of our openjdk:9 image from October 18, which is before many of the stackdriver fixes for java 9. I'll re-release an updated version and then will give it a try.

**Comment by ChengyuanZhao** [comment]
The runtimes-builder image used for appengine deployments has been updated and now sparkjava example works in cloud debugger.
