### ISSUE TITLE
Request for supporting Java 10 RunTime

### ISSUE THREAD

**Issue by balamuru** [GoogleCloudPlatform/openjdk-runtime#178]
When will Java 10 be supported in GCP? Java 10 has some neat enhancements intended to facilitate execution in containerized environments  (CPU awareness, heap %  selection) . http://www.oracle.com/technetwork/java/javase/10-relnote-issues-4108729.html

Thanks

**Comment by wyaeld** [comment]
@meltsufin any chance of a response on this?  We are looking to use 10 for development since the container integration makes things easier, but currently look to use Google maintained base images.

**Comment by meltsufin** [comment]
I'm not aware of any plans to build a Java 10 runtime.
Maybe Java 11 as it's an LTS release, but that's not my call.
I would suggest getting in touch with Cloud Support to communicate such feature requests.

**Comment by nealeu** [comment]
I think it's important to allow people to move forwards on JDK 11 and now 12.
In addition to the key container features from JDK10 (https://www.oracle.com/technetwork/java/javase/10-relnote-issues-4108729.html#JDK-8146115), there are now other opportunities to take advantage of in JDK12 for containers, most notably [Promptly Return Unused Committed Memory](https://openjdk.java.net/jeps/346).

There is also the issue that JDK8 is no longer supported with public updates.

Are pull requests invited on this?

**Comment by meltsufin** [comment]
@dlorenc WDYT?

**Comment by gregw** [comment]
As openjdk9 has now gone from stretch-backports, we can no longer build jdk9, so I think it will have to be 11 for now... with 12 soon.
Stand by for a PR....

**Comment by nealeu** [comment]
Thanks @gregw
