### ISSUE TITLE
Use specific version libssl to break out of cached docker layer

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/openjdk-runtime#18]
The docker layer for the `apt-get install libssl` will continue to use the old libssl version, even if there was a new version released.

We should change the build (somehow) to always rebuild that layer.

**Comment by gregw** [comment]
Can you explain this a bit more?   In the Dockerfile we have:
```
ADD sid.list /etc/apt/sources.list.d/
RUN apt-get -y update \
 && apt-get -y -q --no-install-recommends install \
    libssl1.0.2 \
    openssl \
```
which is there to force the 1.0.2 version.   Are you saying that is a subsequent layer installs `libssl` then it will get a different version?

**Comment by meltsufin** [comment]
Do you guys think this even belongs in the openjdk image? Should the base image for all runtimes install libssl?

**Comment by meltsufin** [comment]
Obsolete. We're no longer installing libssl.
