### ISSUE TITLE
Write Container Structure Tests

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/openjdk-runtime#20]
https://github.com/GoogleCloudPlatform/runtimes-common/tree/master/structure_tests

**Comment by meltsufin** [comment]
One of the tests should be to verify the existence of `/etc/ssl/certs/java/cacerts`. See #24.

**Comment by aslo** [comment]
Closed by https://github.com/GoogleCloudPlatform/openjdk-runtime/pull/35
