### ISSUE TITLE
Build fails because openjdk-8-jre is not found

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/openjdk-runtime#21]
```
$mvn install
...
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.13:build (build) on project openjdk8: Exception caught: The command '/bin/sh -c echo 'deb http://httpredir.debian.org/debian jessie-backports main' > /etc/apt/sources.list.d/jessie-backports.list  && apt-get -q update  && apt-get -y -q --no-install-recommends install     ca-certificates     openjdk-8-jre=8u102'-*'     netbase     wget     unzip  && apt-get clean  && rm /var/lib/apt/lists/*_*' returned a non-zero code: 100 -> [Help 1]
```

More detailed:

```
$/bin/sh -c echo 'deb http://httpredir.debian.org/debian jessie-backports main' > /etc/apt/sources.list.d/jessie-backports.list  && apt-get -q update  && apt-get -y -q --no-install-recommends install     ca-certificates     openjdk-8-jre=8u102'-*'     netbase     wget     unzip  && apt-get clean  && rm /var/lib/apt/lists/*_*

Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Ign http://httpredir.debian.org jessie InRelease
Get:2 http://httpredir.debian.org jessie-updates InRelease [145 kB]
Get:3 http://httpredir.debian.org jessie Release.gpg [2373 B]
Get:4 http://security.debian.org jessie/updates/main amd64 Packages [407 kB]
Get:5 http://httpredir.debian.org jessie Release [148 kB]
Get:6 http://httpredir.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Get:7 http://httpredir.debian.org jessie/main amd64 Packages [9064 kB]
Fetched 9847 kB in 2s (3552 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
E: Unable to locate package openjdk-8-jre
```

**Comment by joakime** [comment]
`openjdk-8-jre` is part of the unstable/sid suite in debian.

https://packages.debian.org/unstable/java/openjdk-8-jre

According to debian.org, there is no stable release of `openjdk-8-jre`

https://packages.debian.org/stable/java/openjdk-8-jre (will return an error)

stable/jessie only has `openjdk-7-jre` as its latest.

https://packages.debian.org/stable/java/openjdk-7-jre

**Comment by joakime** [comment]
Move the install of `openjdk-8-jre` down to [the sid section](https://github.com/GoogleCloudPlatform/openjdk-runtime/blob/4cac10bb37651b40a2ca38f8d28edecda9dce2a8/openjdk8/src/main/docker/Dockerfile#L41-L43) in the Dockerfile and it should start to work.

**Comment by joakime** [comment]
`openjdk-8-jre` is also listed in `jessie-backports` (currently at version `8u111`).

https://packages.debian.org/jessie-backports/openjdk-8-jre

Of note, there is also a `openjdk-8-jre-headless` which seems like a good fit for this image, and its available at version `8u102` as well.

https://packages.debian.org/jessie-backports/openjdk-8-jre-headless

**Comment by meltsufin** [comment]
@joakime Do you also get an error when you run `mvn clean install` on this repo? I'm trying to see if this is due to my environment because this build used to work.

**Comment by joakime** [comment]
Yes, the build fails for me with 8u102, but not with 8u111.

The 8u102 version is not present in the `Packages.gz` on the debian repos, so its not possible to install the 8u102 version anymore using the version qualifier found in commit 4cac10bb37651b40a2ca38f8d28edecda9dce2a8

If I use commit 056e113ca2174acaeb4db3f24a3131dad2006644 (the parent of the above commit) to build it works (this is the commit before the version qualified commit)

The Dockerfile in this prior commit looks like this:  https://github.com/GoogleCloudPlatform/openjdk-runtime/blob/056e113ca2174acaeb4db3f24a3131dad2006644/openjdk8/src/main/docker/Dockerfile

**Comment by meltsufin** [comment]
For me even 8u111 fails, but I think that is due to my environment.
