### ISSUE TITLE
Consider using package openjdk-8-jre-headless instead

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/openjdk-runtime#23]
The openjdk-8-jre-headless seems like a good fit for a docker image (which obviously has no framebuffer or UI).

**Comment by meltsufin** [comment]
Yes, it sounds like a good fit, but I wonder if anyone might be doing something weird in their apps with the UI classes like image processing that will break. In any case, it's definitely worth considering. How much smaller is the package vs. the regular openjdk-8-jre?
