### ISSUE TITLE
Do we still need the Debian CA Certificates workaround in Dockerfile?

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/openjdk-runtime#24]
See: https://github.com/GoogleCloudPlatform/openjdk-runtime/blob/master/openjdk8/src/main/docker/Dockerfile#L35

```
# workaround for https://bugs.debian.org/775775
RUN /var/lib/dpkg/info/ca-certificates-java.postinst configure
```

**Comment by joakime** [comment]
Remove it, try it without that line.

If the file `/etc/ssl/certs/java/cacerts` doesn't exist, then we still have the bug and need that.

**Comment by meltsufin** [comment]
Just tried and it's there. So, I guess we don't need this line anymore.
