### ISSUE TITLE
Do we still need the upgrade to OpenSSL 1.0.2 in the Dockerfile

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/openjdk-runtime#25]
If this is still needed, maybe it belongs in the base image.

```
# Upgrade to OpenSSL 1.0.2 (via sid)
ADD sid.list /etc/apt/sources.list.d/
RUN apt-get -y update \
 && apt-get -y -q --no-install-recommends install \
    libssl1.0.2 \
    openssl \
# Cleanup sid references
 && rm /etc/apt/sources.list.d/sid.list \
 && apt-get -y update \
# Cleanup apt-get temporary files
 && apt-get -y -q upgrade \
 && apt-get -y -q autoremove
```

**Comment by joakime** [comment]
History of the addition of the openssl 1.0.2 artifact can be found at ...

 * https://github.com/grpc/grpc-java/blob/master/SECURITY.md#tls-with-openssl
 * https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/issues/115
 * https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/issues/143

**Comment by meltsufin** [comment]
@dlorenc This sounds like it would be beneficial to all runtimes. Do you think it should be pulled into the base image?

**Comment by meltsufin** [comment]
Also, it looks like the `libssl1.0.2` line is redundant because the current version of OpenSSL is 1.1.0c and it comes with libssl1.1.

@lesv FYI

**Comment by lesv** [comment]
You might wish to reach out to Eric J. or Louis R. of the gRPC teams about this.  (That's why it's there).

**Comment by lesv** [comment]
For Java, we now use BoringSSL, (ie OpenSSL is no longer used)

**Comment by meltsufin** [comment]
Thanks, Les. It sounds like it's no longer needed, but I would like to get a confirmation from the gRPC team. Do you have Eric's and Louis's github handles?

**Comment by lesv** [comment]
They aren't project members so I couldn't use them.  I think both are close to their ldaps.

**Comment by meltsufin** [comment]
Confirmed that this is no longer needed because BoringSSL is now bundled with the gRPC/client libs.

**Comment by joakime** [comment]
What about those folks using older grpc releases on this openjdk-runtime image?
