### ISSUE TITLE
Use GAE_MEMORY_MB * 0.8 for JVM heap default

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/openjdk-runtime#3]
The default `HEAP_SIZE` configuration in setup-env.bash should be set as follows:
If `GAE_MEMORY_MB` is present:
**heap_size = GAE_MEMORY_MB * 0.8**
Otherwise
**heap_size = (/proc/meminfo - 400MB) * 0.8**

**Comment by meltsufin** [comment]
Resolved via #13
