### ISSUE TITLE
Remove logging module

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/openjdk-runtime#30]
Once https://github.com/GoogleCloudPlatform/jetty-runtime/issues/68 is complete, there are no users of the JSON log formatter in the logging module, so it should be removed.

**Comment by tanin47** [comment]
Could you elaborate on what logging module you'll remove? I am using JSON logging with openjdk-image right now. I just want to make sure I can continue to use it.

Currently, I'm writing JSON logs to `/var/log/app_engine/app-test.json`; it seems to work well. Thank you!

**Comment by gregw** [comment]
@tanin47 we have removed the [com.google.cloud.runtimes.logging.JsonFormatter](https://github.com/GoogleCloudPlatform/openjdk-runtime/blob/8-2016-12-21_16_43/logging/src/main/java/com/google/cloud/runtimes/logging/JsonFormatter.java) class.    Are you using this class directly?   

Note that it has already been removed and this issue should have been closed. Will leave open until we determine if you are using it or not.

**Comment by tanin47** [comment]
Ok, I've got it now. And, no, I am not using that class. I'm using `net.logstash.logback.encoder.LogstashEncoder`. We are good. Thank you.

**Comment by meltsufin** [comment]
@tanin47 Can you share your logging configuration for the benefit of others who might want to use it?

**Comment by tanin47** [comment]
Definitely! Here's is `my logback.xml`:

```
<!-- https://www.playframework.com/documentation/latest/SettingsLogger -->
<configuration>
    <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>/var/log/app_engine/app-play.json</file>
        <append>true</append>
        <rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
            <fileNamePattern>/var/log/app_engine/rolled-app-play-%i.json</fileNamePattern>
            <minIndex>1</minIndex>
            <maxIndex>10</maxIndex>
        </rollingPolicy>
        <triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
            <maxFileSize>5MB</maxFileSize>
        </triggeringPolicy>
        <encoder class="net.logstash.logback.encoder.LogstashEncoder">
            <includeContext>false</includeContext>
            <fieldNames>
                <thread>[ignore]</thread>
                <levelValue>[ignore]</levelValue>
                <logger>logger</logger>
                <version>[ignore]</version>
            </fieldNames>
        </encoder>
    </appender>

    <logger name="play" level="INFO" />
    <logger name="application" level="DEBUG" />

    <root level="INFO">
        <appender-ref ref="FILE" />
    </root>
    <shutdownHook/>
</configuration>
```

Please note that rolling logs is essential.

And, in `build.sbt`, we include the below library:

```
libraryDependencies ++= Seq(
  "net.logstash.logback" % "logstash-logback-encoder" % "4.0",
  "com.typesafe.scala-logging" %% "scala-logging" % "3.1.0"
)
```

And, in the code, we can write JSON logs with extra fields as shown below:

```
import net.logstash.logback.marker.Markers._

import com.typesafe.scalalogging.{Logger => ScalaLogger}
import net.logstash.logback.marker.Markers._
import org.slf4j.Marker
import play.api.{Logger => PlayLogger}

import scala.collection.JavaConversions._
import scala.language.implicitConversions

object Logger {
  def getLogger: ScalaLogger = {
    ScalaLogger(PlayLogger(new Throwable().getStackTrace()(2).getClassName.stripSuffix("$")).logger)
  }

  implicit def mapToMapEntriesAppendingMarker[K, V](m: Map[K, V]): Marker = {
    append("extras", m: java.util.Map[K, V])
  }
}


import Logger._

val logger = getLogger
logger.info(Map("some-field" -> "some-value"), "some-message")
```

**Comment by meltsufin** [comment]
@tanin47 This is great! Thanks for sharing!
