### ISSUE TITLE
Add `env JAVA_OPTS="$JAVA_OPTS"` to `exec "$@"`

### ISSUE THREAD

**Issue by tanin47** [GoogleCloudPlatform/openjdk-runtime#43]
At this line: https://github.com/GoogleCloudPlatform/openjdk-runtime/blob/master/openjdk8/src/main/docker/docker-entrypoint.bash#L21

Maybe we change it to `exec env JAVA_OPTS="$JAVA_OPTS" "$@" 2>&1`? (I'm not sure if `2>&1` is needed. Suggestion welcomed).

I was using Scala Playframework, and JAVA_OPTS wasn't set properly. I have to make my own docker-entrypoint.bash.

Making this change would allow me to get rid of my own docker-entrypoint.bash.

**Comment by meltsufin** [comment]
`JAVA_OPTS` is set in [setup-env.bash](https://github.com/GoogleCloudPlatform/openjdk-runtime/blob/master/openjdk8/src/main/docker/setup-env.bash#L29), which is only invoked in the `docker-entrypoint.bash` if the run command starts with `java` or some other argument that is not an executable. What does your docker run command look like?

**Comment by tanin47** [comment]
For playframework, we run the bash script generated by `sbt dist`. The script eventually runs `java` with a lot of arguments, and, fortunately, the script uses the JAVA_OPTS env.

Here's the script template: `https://github.com/sbt/sbt-native-packager/blob/master/src/main/resources/com/typesafe/sbt/packager/archetypes/scripts/bash-template#L297`

Here's my docker run command:

```
CMD ["bin/myappname", "-Dlogger.file=conf/prod.xml", "-Dconfig.file=conf/prod.conf",  "-Dplay.crypto.secret=fakesecret", "-Dhttp.port=8080"]
```

I make my own docker-entrypoint.bash, and this is how it looks like:

```
#!/bin/bash
source /setup-env.bash \
  && exec env JAVA_OPTS="$JAVA_OPTS" "$@" 2>&1
```

**Comment by meltsufin** [comment]
If there is a way to start the app directly via the `java` executable, then you wouldn't need the custom CMD or the modified `docker-entrypoint.bash`. I would recommend looking into that option.

I'm not sure about modifying the actual runtime image the way you suggested to accommodate the Scala Playframework usecase. If the usecase was more generic, it would make more sense, but otherwise, extending the runtime image with a custom Dockerfile seems to be the most appropriate solution.

**Comment by meltsufin** [comment]
@tanin47 On a second thought, if we simply added `export JAVA_OPTS` line before the `exec "$@"` in `docker-entrypoint.bash`, would it solve your issue?

**Comment by tanin47** [comment]
> If there is a way to start the app directly via the java executable, then you wouldn't need the custom CMD or the modified docker-entrypoint.bash. I would recommend looking into that option.
> @tanin47 On a second thought, if we simply added export JAVA_OPTS line before the exec "$@" in docker-entrypoint.bash, would it solve your issue?

This would be helpful. I'll be able to get rid of my docker-entrypoint.bash completely. (One fewer file to maintain)

But I need to verify first whether `export` works as expected. There is some weird issue with `export` inside a bash script. I'll try and report back.

Thank you!

**Comment by gregw** [comment]
@tanin47 The docker-entrypoint has been written as it is so that follows the docker standard practises that easily allow other args and/or commands to be run in the image.    I think that it is worth the effort to use the standard docker-entrypoint, potentially with modifications to fit your requirements.

**Comment by tanin47** [comment]
I confirm that adding `export JAVA_OPTS="$JAVA_OPTS"` in docker-entrypoint.bash works as well. 

I also notice that `setup-env.bash` is only invoked if the first argument is not executable. Our first argument is executable. This would need to be fixed.

Is there a downside for running setup-env.bash every time? The users (who use this image) would expect JAVA_OPTS to be set properly regardless how their commands look like.

**Comment by gregw** [comment]
I don't see any problem running setup-env.bash all of the time.   I also think the script should export all the variables it sets.   I'll prepare a PR...

**Comment by tanin47** [comment]
Thank you! This change is super helpful. Please let me know when the image is deployed. I'll test it promptly.

**Comment by tanin47** [comment]
Is this deployed yet?

**Comment by meltsufin** [comment]
Yes, and it will be made `:latest` soon.
For now, try using this image: `gcr.io/google-appengine/jetty:9.4-2017-01-26_21_46`

**Comment by tanin47** [comment]
Hmm.. I can't make the jetty image work. Do you have the openjdk version?

**Comment by tanin47** [comment]
I tested against `gcr.io/google-appengine/openjdk:8-2017-01-26_21_19`

It seems to work. I only need CMD command and can remove my own `docker-entrypoint.bash`. Thank you for making this change.

**Comment by meltsufin** [comment]
My mistake, sorry. You found the right openjdk image.
