### ISSUE TITLE
Verify that JRE 7 is not installed via ca-certificates-java

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/openjdk-runtime#55]
We're installing [ca-certificates-java](https://packages.debian.org/jessie-backports/ca-certificates-java) as a requirement for the openjdk, but it seems to depend on JRE 7. We need to make sure that we're not polluting the image with JRE 7.

**Comment by balopat** [comment]
1. The dependency list is indeed a bit confusing but I interpret it as following: 

ca-certifactes-java depends on openjdk-7-jre-headless OR  java7-runtime-headless which is a virtual package provided by openjdk-8-jre-headless

Thus, openjdk-8-jre-headless satisfies the dependencies. 

2. based on the latest build (verified locally too), it seems that there are no jre7, java7, jdk7 installations:

````
$ docker run gcr.io/google-appengine/openjdk apt list | grep -E '(java|jre)'

WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.

ca-certificates-java/now 20161107~bpo8+1 all [installed,local]
java-common/now 0.52 all [installed,local]
openjdk-8-jre-headless/now 8u131-b11-1~bpo8+1 amd64 [installed,local]
````

**Comment by meltsufin** [comment]
Can you add structure test to verify this automatically? See #35 for reference. Thanks!
