### ISSUE TITLE
cdbg_extra_class_path arguments are invalid for Jar based deployments

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/openjdk-runtime#64]
The image passes:
`--cdbg_extra_class_path=/webapps/root/WEB-INF/classes:/webapps/root/WEB-INF/lib`

as a fragment of:
```
java -showversion -agentpath:/opt/cdbg/cdbg_java_agent.so=--log_dir=/var/log/app_engine,--logtostderr=false,--cdbg_extra_class_path=/webapps/root/WEB-INF/classes:/webapps/root/WEB-
INF/lib -Xms491M -Xmx491M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:+PrintCommandLineFlags -jar /app/spring-boot-simple-5.0.jar
```

which causes the /var/log/app_engine/cdbg_java_agent.INFO to contain:

```
cdbg_java_agent.8c8c13cfad57.invalid-user.log.INFO.20170228-155954.1  cdbg_java_agent.8c8c13cfad57.invalid-user.log.WARNING.20170228-155955.1  cdbg_java_agent.INFO  cdbg_java_agent.WARNING  custom_logs
root@8c8c13cfad57:/# cat /var/log/app_engine/cdbg_java_agent.INFO
Log file created at: 2017/02/28 15:59:54
Running on machine: 8c8c13cfad57
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0228 15:59:54.725625    15 jvmti_globals.cc:336] Build time: Jan  3 2017 09:10:03
I0228 15:59:54.725790    15 jvmti_agent.cc:157] Java debuglet initialization started
I0228 15:59:54.726048    15 jvmti_agent.cc:191] Java debuglet initialization completed
I0228 15:59:54.804965    15 jvmti_agent.cc:202] Java VM started
I0228 15:59:54.809967    15 jvmti_agent.cc:212] JvmtiAgent::JvmtiOnVMInit initialization time: 5007 microseconds
I0228 15:59:54.810044    26 jvmti_agent_thread.cc:99] Agent thread started: CloudDebugger_main_worker_thread
I0228 15:59:54.810212    26 jvm_internals.cc:376] Loading internals from /opt/cdbg/cdbg_java_agent_internals.jar
I0228 15:59:55.224081    26 jni_logger.cc:31] Initializing ClassPathLookup, default classpath: true, extra classpath: [/webapps/root/WEB-INF/classes, /webapps/root/WEB-INF/lib], config: null
I0228 15:59:55.286089    26 jni_logger.cc:31] Total size of indexed resources database: 1432 bytes
I0228 15:59:55.329637    26 jvm_internals.cc:132] ClassPathLookup constructor time: 118480 microseconds
W0228 15:59:55.777546    26 jni_logger.cc:46] Failed to compute hash of application file /webapps/root/WEB-INF/classes
java.nio.file.NoSuchFileException: /webapps/root/WEB-INF/classes
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at com.google.devtools.cdbg.debuglets.java.UniquifierComputer.appendBinaryFile(Unknown Source)
        at com.google.devtools.cdbg.debuglets.java.UniquifierComputer.append(Unknown Source)
        at com.google.devtools.cdbg.debuglets.java.UniquifierComputer.<init>(Unknown Source)
        at com.google.devtools.cdbg.debuglets.java.ClassPathLookup.computeDebuggeeUniquifier(Unknown Source)
        at com.google.devtools.cdbg.debuglets.java.GcpHubClient.getDebuggeeInfo(Unknown Source)
        at com.google.devtools.cdbg.debuglets.java.GcpHubClient.registerDebuggee(Unknown Source)
W0228 15:59:55.777968    26 jni_logger.cc:46] Failed to compute hash of application file /webapps/root/WEB-INF/lib
java.nio.file.NoSuchFileException: /webapps/root/WEB-INF/lib
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at com.google.devtools.cdbg.debuglets.java.UniquifierComputer.appendBinaryFile(Unknown Source)
        at com.google.devtools.cdbg.debuglets.java.UniquifierComputer.append(Unknown Source)
        at com.google.devtools.cdbg.debuglets.java.UniquifierComputer.<init>(Unknown Source)
        at com.google.devtools.cdbg.debuglets.java.ClassPathLookup.computeDebuggeeUniquifier(Unknown Source)
        at com.google.devtools.cdbg.debuglets.java.GcpHubClient.getDebuggeeInfo(Unknown Source)
        at com.google.devtools.cdbg.debuglets.java.GcpHubClient.registerDebuggee(Unknown Source)
I0228 15:59:57.652278    26 jni_logger.cc:31] Debuggee gcp:1031550152456:8402ef630c825e73 registered: {"debuggee":{"id":"gcp:1031550152456:8402ef630c825e73","project":"1031550152456","uniquifier":"8DA069F1CA0B61EAFC6587E57F9FEE9411FF23E4","descr
iption":"paflynn-demo-project","agentVersion":"google.com/java-gcp/@2"}}, agent version: 2.8
I0228 15:59:57.652299    26 jvmti_agent.cc:414] Attaching Java debuglet
I0228 15:59:57.652760    26 rate_limit.cc:122] CPU count: 1
I0228 15:59:57.652768    26 debugger.cc:97] Initializing Java debuglet

```

It's unclear what impact this has, as CDB appears broken for Java Flex for other reasons.

**Comment by meltsufin** [comment]
I believe CDB was broken for other reasons and should be working now.
@joaoandremartins, can you verify that CDB is working.
Also, although this error should be harmless, the `--cdbg_extra_class_path parameter` is only needed for the jetty runtime. So we should probably move it to be only provided in jetty.

**Comment by joaoandremartins** [comment]
I verified that the Cloud Debugger still works for a JAR app deployed to App Engine Flexible, despite the logged exceptions at `/var/log/app_engine/app/cdbg_java_agent.INFO`.

The `--cdbg_extra_class_path` flag is being added from an external file:

`[DBG_AGENT="$( RUNTIME_DIR=$JETTY_BASE /opt/cdbg/format-env-appengine-vm.sh )"](https://github.com/GoogleCloudPlatform/openjdk-runtime/blob/master/openjdk8/src/main/docker/setup-env.d/20-debug-env.bash#L11)`

`[ADD https://storage.googleapis.com/cloud-debugger/appengine-java/current/cdbg_java_agent.tar.gz /opt/cdbg/](https://github.com/GoogleCloudPlatform/openjdk-runtime/blob/master/openjdk8/src/main/docker/Dockerfile#L37)`

It doesn't seem like we can do away this package completely. To turn the flag off for anything but the Jetty image, `/opt/cdbg/format-env-appengine-vm.sh` should be changed. e.g.,

```
APP_WEB_INF_DIR="${RUNTIME_DIR}/webapps/root/WEB-INF"

ARGS="-agentpath:${CDBG_ROOT}/cdbg_java_agent.so="
ARGS+="--log_dir=/var/log/app_engine"
ARGS+=",--logtostderr=false"
if [ "$GAE_IMAGE_NAME" = "jetty" ]; then
  ARGS+=",--cdbg_extra_class_path=${APP_WEB_INF_DIR}/classes:${APP_WEB_INF_DIR}/lib"
fi
```

On the openjdk image, $JETTY_BASE isn't set, therefore $RUNTIME_DIR isn't set, therefore we end up with a `/webapps/root/WEB-INF/classes:/webapps/root/WEB-INF/lib` classpath, which doesn't exist, hence the exception.

**Comment by joaoandremartins** [comment]
I filed internal issue #37908366 with the CDB team, so they add the suggested fix to format-env-appengine-vm.sh.

@aslo can you please take a look, since Mike is away this week?

**Comment by aslo** [comment]
One concern with this solution - it doesn't account for other web server runtimes (including tomcat, which is coming soon). Also, it looks like the `$APP_WEB_INF_DIR` variable is set to a jetty-specific path.

Maybe it would be better to instead for the runtime to set `$APP_WEB_INF_DIR`. Then the cloud debug script could just do something like:

```
if [ ! -z "$APP_WEB_INF_DIR" ]; then
  ARGS+=",--cdbg_extra_class_path=${APP_WEB_INF_DIR}/classes:${APP_WEB_INF_DIR}/lib"
fi
```

What do you think?

**Comment by joaoandremartins** [comment]
I think you meant `if [ ! -z "${RUNTIME_DIR}" ]; then`, but yes, I agree your solution is more extensible.

**Comment by aslo** [comment]
No, I'm saying the $APP_WEB_INF_DIR should be set by the runtime, since that's specific to the web server (it will be a different path in jetty vs tomcat). Then this script can just check for that variable's presence.

**Comment by joaoandremartins** [comment]
`$APP_WEB_INF_DIR` is never empty because of the way its assigned its value.

`APP_WEB_INF_DIR="${RUNTIME_DIR}/webapps/root/WEB-INF"`

**Comment by joaoandremartins** [comment]
The remote `/opt/cdbg/format-env-appengine-vm.sh` file now contains the suggested fix.

@aslo mentioned an even better fix, which is for each runtime to specify `$APP_WEB_INF_DIR`, instead of the openjdk image as it's currently happening. I think it's easier to piggyback this change when other runtimes are launched, but I can be convinced otherwise.

**Comment by meltsufin** [comment]
We still have the problem of the configuration being jetty-specific.
```
DBG_AGENT="$( RUNTIME_DIR=$JETTY_BASE /opt/cdbg/format-env-appengine-vm.sh )"
```

@joaoandremartins Maybe change it to:
```
DBG_AGENT="$( RUNTIME_DIR=$RUNTIME_DIR /opt/cdbg/format-env-appengine-vm.sh )"
```
and then define `RUNTIME_DIR = $JETTY_BASE` in the Jetty runtime.

**Comment by gregw** [comment]
The openjdk-runtime could just only define RUNTIME_DIR to a neutral default value if it is not already defined..

The jetty-runtime could then drop in a `/setup-env.d/19-debug-jetty-env.bash` file that sets the RUNTIME_DIR to a jetty specific value and other extended images could do the same.    

It perhaps would be better to have a name like DBG_WEBAPP_DIR and have the `20-debug-env.bash` script convert to whatever the `format-env-appengine-vm.sh` needs.  This decouples multiple env scripts from the current impl of cdbg.

**Comment by meltsufin** [comment]
The `format-env-appengine-vm.sh` file looks like this now:
```sh
if [[ -n "${CDBG_DISABLE}" ]]; then
  >&2 echo "CDBG_DISABLE is set, Java Cloud Debugger will not be loaded"
  exit
fi

APP_WEB_INF_DIR="${RUNTIME_DIR}/webapps/root/WEB-INF"
CDBG_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ARGS="-agentpath:${CDBG_ROOT}/cdbg_java_agent.so="
ARGS+="--log_dir=/var/log/app_engine"
ARGS+=",--alsologtostderr=true"

# When using Jetty/Tomcat images, the debugger should also read the
# WEB-INF/classes and WEB-INF/lib directories. When using the OpenJDK
# image (which deploys a JAR), this is not necessary.
if [[ ! -z "${RUNTIME_DIR}" ]]; then
  ARGS+=",--cdbg_extra_class_path=${APP_WEB_INF_DIR}/classes:${APP_WEB_INF_DIR}/lib"
fi

echo "${ARGS}"
```

So, I think it's best to just keep `RUNTIME_DIR` undefined in openjdk, and set it where it's needed.

Ultimately, each runtime should just set `APP_WEB_INF_DIR`, and `format-env-appengine-vm.sh` would be changed to not use `RUNTIME_DIR` at all.
@joaoandremartins WDYT?

**Comment by gregw** [comment]
`APP_WEB_INF_DIR` is a better name than `RUNTIME_DIR`, but it would still be nice to have `CDBG` in the name so other images know why they are setting it.

Note also that in the code above, the `APP_WEB_INF_DIR` is set from `RUNTIME_DIR` before it is checked for non null status.

**Comment by meltsufin** [comment]
How about this for `format-env-appengine-vm.sh`?
```sh
if [[ -n "${CDBG_DISABLE}" ]]; then
  >&2 echo "CDBG_DISABLE is set, Java Cloud Debugger will not be loaded"
  exit
fi

CDBG_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ARGS="-agentpath:${CDBG_ROOT}/cdbg_java_agent.so="
ARGS+="--log_dir=/var/log/app_engine"
ARGS+=",--alsologtostderr=true"

# When using Jetty/Tomcat images, the debugger should also read the
# WEB-INF/classes and WEB-INF/lib directories. When using the OpenJDK
# image (which deploys a JAR), this is not necessary.
if [[ ! -z "${CDBG_APP_WEB_INF_DIR}" ]]; then
  ARGS+=",--cdbg_extra_class_path=${CDBG_APP_WEB_INF_DIR}/classes:${CDBG_APP_WEB_INF_DIR}/lib"
fi

echo "${ARGS}"
```

**Comment by joaoandremartins** [comment]
@meltsufin that solution works, as long as `${CDBG_APP_WEB_INF_DIR}` isn't set to anything if `${RUNTIME_DIR}` is empty.
I'll try to get started on this today, after releasing the new Jetty image.

**Comment by meltsufin** [comment]
Actually, I think we still need to support `RUNTIME_DIR` for backwards compatibility:
```sh
if [[ -n "${CDBG_DISABLE}" ]]; then
  >&2 echo "CDBG_DISABLE is set, Java Cloud Debugger will not be loaded"
  exit
fi

CDBG_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ARGS="-agentpath:${CDBG_ROOT}/cdbg_java_agent.so="
ARGS+="--log_dir=/var/log/app_engine"
ARGS+=",--alsologtostderr=true"

# When using Jetty/Tomcat images, the debugger should also read the
# WEB-INF/classes and WEB-INF/lib directories. When using the OpenJDK
# image (which deploys a JAR), this is not necessary.
if [[ ! -z "${RUNTIME_DIR}" ]]; then
  APP_WEB_INF_DIR="${RUNTIME_DIR}/webapps/root/WEB-INF"
fi
if [[ ! -z "${CDBG_APP_WEB_INF_DIR}" ]]; then
  ARGS+=",--cdbg_extra_class_path=${CDBG_APP_WEB_INF_DIR}/classes:${CDBG_APP_WEB_INF_DIR}/lib"
fi

echo "${ARGS}"
```

**Comment by gregw** [comment]
@meltsufin LGTM
