### ISSUE TITLE
Default docker image version label should contain a unique build id

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/openjdk-runtime#8]

**Comment by joakime** [comment]
commit id hashes are not unique enough.
the same commit id will be in many branches and pull requests.

you can still have collisions in the docker image tags and deployed uris (for testing)

**Comment by meltsufin** [comment]
@joakime What makes you say that the git commit hash is not unique enough? If you build by checking out a specific commit, wouldn't it always build from the exact same source?
